
package alom.bank.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://service.server.bank.alom/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param typeCompte
     * @param client
     * @return
     *     returns alom.bank.client.Compte
     * @throws ClientInexistantException_Exception
     * @throws TypeCompteInvalideException_Exception
     * @throws CompteInexistantException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recupererCompte", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.RecupererCompte")
    @ResponseWrapper(localName = "recupererCompteResponse", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.RecupererCompteResponse")
    public Compte recupererCompte(
        @WebParam(name = "client", targetNamespace = "")
        Client client,
        @WebParam(name = "typeCompte", targetNamespace = "")
        TypeCompte typeCompte)
        throws ClientInexistantException_Exception, CompteInexistantException_Exception, TypeCompteInvalideException_Exception
    ;

    /**
     * 
     * @param typeCompte
     * @param client
     * @return
     *     returns alom.bank.client.Compte
     * @throws ClientInexistantException_Exception
     * @throws TypeCompteInvalideException_Exception
     * @throws CompteDejaExistantException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "creerCompte", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.CreerCompte")
    @ResponseWrapper(localName = "creerCompteResponse", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.CreerCompteResponse")
    public Compte creerCompte(
        @WebParam(name = "client", targetNamespace = "")
        Client client,
        @WebParam(name = "typeCompte", targetNamespace = "")
        TypeCompte typeCompte)
        throws ClientInexistantException_Exception, CompteDejaExistantException_Exception, TypeCompteInvalideException_Exception
    ;

    /**
     * 
     * @param dateNaissance
     * @param prenom
     * @param nom
     * @return
     *     returns alom.bank.client.Client
     * @throws ClientDejaExistantException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "creerClient", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.CreerClient")
    @ResponseWrapper(localName = "creerClientResponse", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.CreerClientResponse")
    public Client creerClient(
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "DateNaissance", targetNamespace = "")
        XMLGregorianCalendar dateNaissance)
        throws ClientDejaExistantException_Exception
    ;

    /**
     * 
     * @param montant
     * @param compte
     * @return
     *     returns double
     * @throws MontantInvalideException_Exception
     * @throws DecouvertNonAutoriseException_Exception
     * @throws CompteInexistantException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retirerArgent", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.RetirerArgent")
    @ResponseWrapper(localName = "retirerArgentResponse", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.RetirerArgentResponse")
    public double retirerArgent(
        @WebParam(name = "compte", targetNamespace = "")
        Compte compte,
        @WebParam(name = "montant", targetNamespace = "")
        double montant)
        throws CompteInexistantException_Exception, DecouvertNonAutoriseException_Exception, MontantInvalideException_Exception
    ;

    /**
     * 
     * @param somme
     * @param compte
     * @return
     *     returns double
     * @throws IllegalArgumentException_Exception
     * @throws CompteInexistantException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterArgent", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.AjouterArgent")
    @ResponseWrapper(localName = "ajouterArgentResponse", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.AjouterArgentResponse")
    public double ajouterArgent(
        @WebParam(name = "compte", targetNamespace = "")
        Compte compte,
        @WebParam(name = "somme", targetNamespace = "")
        double somme)
        throws CompteInexistantException_Exception, IllegalArgumentException_Exception
    ;

    /**
     * 
     * @param dateNaissance
     * @param prenom
     * @param nom
     * @return
     *     returns alom.bank.client.Client
     * @throws ClientInexistantException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recupererClient", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.RecupererClient")
    @ResponseWrapper(localName = "recupererClientResponse", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.RecupererClientResponse")
    public Client recupererClient(
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "DateNaissance", targetNamespace = "")
        XMLGregorianCalendar dateNaissance)
        throws ClientInexistantException_Exception
    ;

    /**
     * 
     * @param compte
     * @return
     *     returns double
     * @throws CompteInexistantException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connaitreSolde", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.ConnaitreSolde")
    @ResponseWrapper(localName = "connaitreSoldeResponse", targetNamespace = "http://service.server.bank.alom/", className = "alom.bank.client.ConnaitreSoldeResponse")
    public double connaitreSolde(
        @WebParam(name = "compte", targetNamespace = "")
        Compte compte)
        throws CompteInexistantException_Exception
    ;

}
