
package alom.bank.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-27T12:27:55.805+02:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "ClientInexistantException", targetNamespace = "http://service.server.bank.alom/")
public class ClientInexistantException_Exception extends Exception {

    private alom.bank.client.ClientInexistantException faultInfo;

    public ClientInexistantException_Exception() {
        super();
    }

    public ClientInexistantException_Exception(String message) {
        super(message);
    }

    public ClientInexistantException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ClientInexistantException_Exception(String message, alom.bank.client.ClientInexistantException clientInexistantException) {
        super(message);
        this.faultInfo = clientInexistantException;
    }

    public ClientInexistantException_Exception(String message, alom.bank.client.ClientInexistantException clientInexistantException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = clientInexistantException;
    }

    public alom.bank.client.ClientInexistantException getFaultInfo() {
        return this.faultInfo;
    }
}
