
package alom.bank.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CompteInexistantException", targetNamespace = "http://service.server.bank.alom/")
public class CompteInexistantException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CompteInexistantException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CompteInexistantException_Exception(String message, CompteInexistantException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CompteInexistantException_Exception(String message, CompteInexistantException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: alom.bank.client.CompteInexistantException
     */
    public CompteInexistantException getFaultInfo() {
        return faultInfo;
    }

}
