
package alom.bank.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-27T12:27:55.943+02:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "IllegalArgumentException", targetNamespace = "http://service.server.bank.alom/")
public class IllegalArgumentException_Exception extends Exception {

    private alom.bank.client.IllegalArgumentException faultInfo;

    public IllegalArgumentException_Exception() {
        super();
    }

    public IllegalArgumentException_Exception(String message) {
        super(message);
    }

    public IllegalArgumentException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IllegalArgumentException_Exception(String message, alom.bank.client.IllegalArgumentException illegalArgumentException) {
        super(message);
        this.faultInfo = illegalArgumentException;
    }

    public IllegalArgumentException_Exception(String message, alom.bank.client.IllegalArgumentException illegalArgumentException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = illegalArgumentException;
    }

    public alom.bank.client.IllegalArgumentException getFaultInfo() {
        return this.faultInfo;
    }
}
