
package alom.bank.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-27T12:27:55.839+02:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "MontantInvalideException", targetNamespace = "http://service.server.bank.alom/")
public class MontantInvalideException_Exception extends Exception {

    private alom.bank.client.MontantInvalideException faultInfo;

    public MontantInvalideException_Exception() {
        super();
    }

    public MontantInvalideException_Exception(String message) {
        super(message);
    }

    public MontantInvalideException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public MontantInvalideException_Exception(String message, alom.bank.client.MontantInvalideException montantInvalideException) {
        super(message);
        this.faultInfo = montantInvalideException;
    }

    public MontantInvalideException_Exception(String message, alom.bank.client.MontantInvalideException montantInvalideException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = montantInvalideException;
    }

    public alom.bank.client.MontantInvalideException getFaultInfo() {
        return this.faultInfo;
    }
}
