
package alom.bank.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TypeCompteInvalideException", targetNamespace = "http://service.server.bank.alom/")
public class TypeCompteInvalideException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TypeCompteInvalideException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TypeCompteInvalideException_Exception(String message, TypeCompteInvalideException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TypeCompteInvalideException_Exception(String message, TypeCompteInvalideException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: alom.bank.client.TypeCompteInvalideException
     */
    public TypeCompteInvalideException getFaultInfo() {
        return faultInfo;
    }

}
