
package alom.bank.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-25T22:58:50.870+02:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "TypeCompteInvalideException", targetNamespace = "http://service.server.bank.alom/")
public class TypeCompteInvalideException_Exception extends Exception {

    private alom.bank.client.TypeCompteInvalideException faultInfo;

    public TypeCompteInvalideException_Exception() {
        super();
    }

    public TypeCompteInvalideException_Exception(String message) {
        super(message);
    }

    public TypeCompteInvalideException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TypeCompteInvalideException_Exception(String message, alom.bank.client.TypeCompteInvalideException typeCompteInvalideException) {
        super(message);
        this.faultInfo = typeCompteInvalideException;
    }

    public TypeCompteInvalideException_Exception(String message, alom.bank.client.TypeCompteInvalideException typeCompteInvalideException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = typeCompteInvalideException;
    }

    public alom.bank.client.TypeCompteInvalideException getFaultInfo() {
        return this.faultInfo;
    }
}
