
package alom.server.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-24T19:09:30.898+02:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "ClientDejaExistantException", targetNamespace = "http://service.server.bank.alom/")
public class ClientDejaExistantException_Exception extends Exception {

    private alom.server.client.ClientDejaExistantException faultInfo;

    public ClientDejaExistantException_Exception() {
        super();
    }

    public ClientDejaExistantException_Exception(String message) {
        super(message);
    }

    public ClientDejaExistantException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ClientDejaExistantException_Exception(String message, alom.server.client.ClientDejaExistantException clientDejaExistantException) {
        super(message);
        this.faultInfo = clientDejaExistantException;
    }

    public ClientDejaExistantException_Exception(String message, alom.server.client.ClientDejaExistantException clientDejaExistantException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = clientDejaExistantException;
    }

    public alom.server.client.ClientDejaExistantException getFaultInfo() {
        return this.faultInfo;
    }
}
