
package alom.server.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-24T19:09:30.790+02:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "CompteInexistantException", targetNamespace = "http://service.server.bank.alom/")
public class CompteInexistantException_Exception extends Exception {

    private alom.server.client.CompteInexistantException faultInfo;

    public CompteInexistantException_Exception() {
        super();
    }

    public CompteInexistantException_Exception(String message) {
        super(message);
    }

    public CompteInexistantException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CompteInexistantException_Exception(String message, alom.server.client.CompteInexistantException compteInexistantException) {
        super(message);
        this.faultInfo = compteInexistantException;
    }

    public CompteInexistantException_Exception(String message, alom.server.client.CompteInexistantException compteInexistantException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = compteInexistantException;
    }

    public alom.server.client.CompteInexistantException getFaultInfo() {
        return this.faultInfo;
    }
}
