
package alom.server.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-24T19:09:30.870+02:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "CompteDejaExistantException", targetNamespace = "http://service.server.bank.alom/")
public class CompteDejaExistantException_Exception extends Exception {

    private alom.server.client.CompteDejaExistantException faultInfo;

    public CompteDejaExistantException_Exception() {
        super();
    }

    public CompteDejaExistantException_Exception(String message) {
        super(message);
    }

    public CompteDejaExistantException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CompteDejaExistantException_Exception(String message, alom.server.client.CompteDejaExistantException compteDejaExistantException) {
        super(message);
        this.faultInfo = compteDejaExistantException;
    }

    public CompteDejaExistantException_Exception(String message, alom.server.client.CompteDejaExistantException compteDejaExistantException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = compteDejaExistantException;
    }

    public alom.server.client.CompteDejaExistantException getFaultInfo() {
        return this.faultInfo;
    }
}
