
package alom.server.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-24T19:09:30.920+02:00
 * Generated source version: 4.0.5
 */

@WebFault(name = "DecouvertNonAutoriseException", targetNamespace = "http://service.server.bank.alom/")
public class DecouvertNonAutoriseException_Exception extends Exception {

    private alom.server.client.DecouvertNonAutoriseException faultInfo;

    public DecouvertNonAutoriseException_Exception() {
        super();
    }

    public DecouvertNonAutoriseException_Exception(String message) {
        super(message);
    }

    public DecouvertNonAutoriseException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DecouvertNonAutoriseException_Exception(String message, alom.server.client.DecouvertNonAutoriseException decouvertNonAutoriseException) {
        super(message);
        this.faultInfo = decouvertNonAutoriseException;
    }

    public DecouvertNonAutoriseException_Exception(String message, alom.server.client.DecouvertNonAutoriseException decouvertNonAutoriseException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = decouvertNonAutoriseException;
    }

    public alom.server.client.DecouvertNonAutoriseException getFaultInfo() {
        return this.faultInfo;
    }
}
